[project]
name = "agri-tech-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Smart Manufacturing Team", email = "user@smartmanufacturing.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
agri-tech-project = "agri_tech_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
